import json
import uuid
from typing import Dict, Any, List, Optional
from openai import AsyncOpenAI
from sqlalchemy.orm import Session
from app.core.config import settings
from app.models.proposal import Proposal, ProposalType, ProposalStatus
from app.models.proposal_request import ProposalRequest, CommunicationType, ProposalRequestStatus
from app.models.resource_allocation import ResourceAllocation
from app.services.proposal.generate_poc import generate_poc
from app.services.proposal.docx_generator import generate_proposal_docx
import logging
from app.services.resource.cost_estimation import match_resources

logger = logging.getLogger(__name__)

# Initialize the OpenAI client asynchronously
client = AsyncOpenAI(
    api_key=settings.OPENAI_API_KEY
)

from typing import Dict, Any
import uuid

async def generate_proposals_for_request(
    db: Session,
    client_id: uuid.UUID,
    proposal_input: Dict[str, Any] = None,
    **kwargs
) -> Dict[str, Any]:
    """
    Generates professional MVP and Full proposals using the finalized
    project estimation from the Resource Allocation Engine.

    The estimation payload already contains the calculated project cost,
    selected resources, resource requirements, timeline, and budget
    feasibility. The AI only generates the proposal content and must not
    modify any financial values.
    """

    if proposal_input is None:
        proposal_input = {}
    proposal_input.update(kwargs)

    mvp_data = proposal_input.get("mvp", {})
    full_data_input = proposal_input.get("full_project", {})
    
    user_input_summary = {
        "proposal_id": proposal_input.get("proposal_id"),
        "project_name": proposal_input.get("project_name"),
        "preferred_technology": proposal_input.get("preferred_technology"),
        "client_budget": proposal_input.get("client_budget"),
        "mvp_estimation": mvp_data,
        "full_project_estimation": full_data_input
    }

    print("\n--- [DATA FLOW] Proposal Generation Engine Started ---")
    print(f"MVP Cost Estimation: {mvp_data.get('total_project_cost')}")
    print(f"Full Project Cost Estimation: {full_data_input.get('total_project_cost')}")
    print(f"MVP Timeline Extracted: {mvp_data.get('timeline_weeks')} Weeks")
    print(f"Full Project Timeline Extracted: {full_data_input.get('timeline_weeks')} Weeks")
    print("------------------------------------------------------\n")

    system_prompt = """
    You are a Senior Technical Director and Pre-Sales Solution Architect with extensive experience in enterprise software consulting, solution architecture, and proposal writing.

Your task is to analyze the provided project estimation data and generate TWO professional software implementation proposals:

1. MVP (Minimum Viable Product)
   - Focus on delivering the client's core business objectives.
   - Include only essential features required for a production-ready first release.
   - Keep the architecture simple, maintainable, and scalable enough for future enhancements.

2. Full Product
   - Present a complete enterprise-grade solution.
   - Include advanced functionality, integrations, reporting, analytics, security, scalability, monitoring, and automation.
   - The Full Product should be significantly more comprehensive than the MVP and should not simply repeat the same content.

IMPORTANT RULES

• The input already contains the finalized project estimation generated by the resource allocation engine.
• The input includes project cost, selected resources, timeline, budget feasibility, and resource requirements.
• NEVER modify, estimate, calculate, or infer any financial values.
• NEVER change the provided timeline duration for the Full Product. However, you MUST dynamically calculate and propose a realistically reduced timeline for the MVP variant based on its narrower scope.
• NEVER change the selected resources.
• Use the exact technology stack that was provided in the input if present.
• Your timeline breakdown phases MUST add up to exactly the timeline you determine for each variant.
• Your responsibility is only to generate professional proposal content.

INFERENCE RULES

If project details are incomplete, intelligently infer and enhance:

- Business domain
- Project description
- Functional scope
- Preferred technology stack
- Technical architecture

The inferred information should remain realistic and consistent with the project requirements.

----------------------------------

Each proposal MUST include:

1. Executive Summary
   - A concise overview of the proposed solution.

2. Technology Stack
   {
      "backend": "",
      "frontend": "",
      "database": "",
      "cloud": "",
      "other_tools": []
   }

3. Solution Architecture
   - Brief explanation of the proposed architecture.

4. Scope
   - Clearly describe what will be delivered.

5. Key Features
   - A detailed list of features included in the proposal.

6. Deliverables
   - List all deliverables to be handed over to the client.

7. Assumptions
   - State all technical and business assumptions.

8. Risks
   - Mention implementation risks and possible mitigation.

9. Acceptance Criteria
   - Define when the project can be considered successfully delivered.

10. Timeline Phases

Generate a realistic implementation roadmap.

Each phase MUST follow this format:

{
    "Phase": "",
    "Duration": "",
    "Output": ""
}

Example:

[
    {
        "Phase": "Requirement Analysis",
        "Duration": "3-5 Days",
        "Output": "Detailed Software Requirement Specification"
    },
    {
        "Phase": "UI/UX Design",
        "Duration": "1 Week",
        "Output": "Interactive UI Prototype"
    }
]

The timeline phases should completely utilize the exact project duration provided in the estimation data, no more and no less.

----------------------------------

MVP Requirements

The MVP should contain only essential functionality.

Typical MVP characteristics:

• Authentication
• Core business workflow
• Basic dashboard
• CRUD operations
• Essential APIs
• Responsive UI
• Basic deployment
• Minimal security

Avoid adding advanced enterprise capabilities.

----------------------------------

Full Product Requirements

The Full Product should include everything from the MVP plus advanced enterprise capabilities such as:

• Role-Based Access Control (RBAC)
• Advanced Admin Dashboard
• Reporting & Analytics
• Notifications
• Audit Logs
• API Integrations
• Workflow Automation
• Performance Optimization
• Monitoring & Logging
• Security Best Practices
• Backup & Recovery
• CI/CD Pipeline
• Scalability Improvements
• Production Readiness

----------------------------------

Return ONLY a valid JSON object with the following structure:

{
    "inferred_project_name": "",
    "inferred_business_domain": "",
    "inferred_project_description": "",
    "inferred_preferred_technology": [],

    "mvp": {
        "executive_summary": "",
        "tech_stack": {},
        "architecture": "",
        "scope": "",
        "key_features": [],
        "deliverables": [],
        "assumptions": "",
        "risks": "",
        "acceptance_criteria": [],
        "estimated_duration_weeks": 0,
        "timeline_phases": [],
        "resource_requirements": []
    },

    "full": {
        "executive_summary": "",
        "tech_stack": {},
        "architecture": "",
        "scope": "",
        "key_features": [],
        "deliverables": [],
        "assumptions": "",
        "risks": "",
        "acceptance_criteria": [],
        "estimated_duration_weeks": 0,
        "timeline_phases": [],
        "resource_requirements": []
    }
}

Return ONLY valid JSON.
Do not include markdown.
Do not include explanations.
Do not include any additional text.
    """
    response = await client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": json.dumps(user_input_summary)}
        ],
        response_format={"type": "json_object"},
        temperature=0.1
    )
    
    generation_content = json.loads(response.choices[0].message.content)
    
    # 2. Extract inferred data
    final_project_name = proposal_input.get("project_name", "Draft Project")
    final_domain = generation_content.get("inferred_business_domain")
    final_desc = generation_content.get("inferred_project_description")
    final_tech = generation_content.get("inferred_preferred_technology", [])

    final_budget = proposal_input.get("client_budget")
    if final_budget is None:
        final_budget = proposal_input.get("budget", 0.0)
    if final_budget is None:
        final_budget = 0.0
    timeline_val = mvp_data.get("timeline_weeks", proposal_input.get("timeline_weeks", "TBD"))
    final_timeline = f"{timeline_val} Weeks" if str(timeline_val).isnumeric() else str(timeline_val)

    estimated_cost = mvp_data.get("total_project_cost", final_budget)
    selected_resources = mvp_data.get("selected_resources", [])
    resource_requirements = mvp_data.get("resource_requirements", [])
    recommended_budget = proposal_input.get("recommended_budget", final_budget)
    is_within_budget = mvp_data.get("is_within_budget", True)
    budget_variance = mvp_data.get("budget_variance_usd", 0)
    
    if not is_within_budget:
        return {
            "proposal_id": proposal_input.get("proposal_id"),
            "possible": False,
            "description": (
                "The requested project cannot be delivered within the client's "
                "specified budget. Please increase the budget or reduce the scope."
            ),
            "estimated_cost": estimated_cost,
            "client_budget": final_budget,
            "budget_variance_usd": budget_variance,
            "mvp": None,
            "full": None
        }

    # 3. Create or Update ProposalRequest record in the database
    existing_request_id = kwargs.get("existing_request_id")
    proposal_request = None
    
    if existing_request_id:
        proposal_request = db.query(ProposalRequest).filter(ProposalRequest.id == existing_request_id).first()
        if proposal_request:
            proposal_request.project_name = final_project_name
            proposal_request.project_description = final_desc
            proposal_request.business_domain = final_domain
            proposal_request.preferred_technology = final_tech
            proposal_request.budget = final_budget
            proposal_request.timeline = final_timeline
            proposal_request.extracted_json = generation_content
            proposal_request.status = ProposalRequestStatus.PROCESSING
            
            # Delete old proposals to replace them with the regenerated ones
            db.query(Proposal).filter(Proposal.request_id == existing_request_id).delete()
            db.flush()

    if not proposal_request:
        proposal_request = ProposalRequest(
            id=uuid.uuid4(),
            client_id=client_id,
            project_name=final_project_name,
            project_description=final_desc,
            business_domain=final_domain,
            preferred_technology=final_tech,
            budget=final_budget,
            timeline=final_timeline,
            communication_type=CommunicationType.FORM,
            extracted_json=generation_content,
            status=ProposalRequestStatus.PROCESSING
        )
        db.add(proposal_request)
        db.flush()

    # 4. Generate MVP Proposal
    mvp_data = generation_content["mvp"]
    mvp_input = proposal_input.get("mvp", {})
    mvp_cost = mvp_input.get("total_project_cost", estimated_cost)

    mvp_proposal = Proposal(
        id=uuid.uuid4(),
        request_id=proposal_request.id,
        proposal_type=ProposalType.MVP,
        tech_stack=mvp_data["tech_stack"],
        estimated_cost=mvp_cost,
        selected_resources={
            "resource_requirements": mvp_input.get("resource_requirements", resource_requirements),
            "selected_resources": mvp_input.get("selected_resources", selected_resources),
            "developer_cost": mvp_input.get("developer_cost"),
            "company_static_cost": mvp_input.get("company_static_cost"),
            "total_project_cost": mvp_cost
        },
        estimated_duration=f"{mvp_data['estimated_duration_weeks']} Weeks",
        scope=mvp_data["scope"],
        assumptions=mvp_data["assumptions"],
        risks=mvp_data["risks"],
        generated_by_ai=True,
        version=1,
        status=ProposalStatus.GENERATED,
        timeline_phases=mvp_data["timeline_phases"]
    )
    db.add(mvp_proposal)

    # 5. Generate Full Product Proposal
    full_data = generation_content["full"]
    full_input = proposal_input.get("full_project", {})
    full_cost = full_input.get("total_project_cost", estimated_cost)
    
    full_proposal = Proposal(
        id=uuid.uuid4(),
        request_id=proposal_request.id,
        proposal_type=ProposalType.FULL,
        tech_stack=full_data["tech_stack"],
        estimated_cost=full_cost,
        selected_resources={
            "resource_requirements": full_input.get("resource_requirements", resource_requirements),
            "selected_resources": full_input.get("selected_resources", selected_resources),
            "developer_cost": full_input.get("developer_cost"),
            "company_static_cost": full_input.get("company_static_cost"),
            "total_project_cost": full_cost
        },
        estimated_duration=f"{full_data['estimated_duration_weeks']} Weeks",
        scope=full_data["scope"],
        assumptions=full_data["assumptions"],
        risks=full_data["risks"],
        generated_by_ai=True,
        version=1,
        status=ProposalStatus.GENERATED,
        timeline_phases=full_data["timeline_phases"]
    )
    db.add(full_proposal)

    proposal_request.status = ProposalRequestStatus.COMPLETED
    db.commit()
    
    def sanitize_resources(resources_dict):
        if not resources_dict:
            return {}
        sanitized = resources_dict.copy()
        # Keep full selected_resources for frontend detailed breakdown proof
        # sanitized.pop("developer_cost", None)
        # sanitized.pop("company_static_cost", None)
        return sanitized

    response_data = {
        "proposal_request_id": str(proposal_request.id),
        "project_name": final_project_name,
        "project_description": final_desc,
        "business_domain": final_domain,
        "preferred_technology": final_tech,
        "client_budget": final_budget,
        "recommended_budget": recommended_budget,
        "estimated_cost": estimated_cost,
        "timeline": final_timeline,
        "proposals": [
            {
                "id": str(mvp_proposal.id),
                "proposal_type": mvp_proposal.proposal_type.value,
                "executive_summary": mvp_data.get("executive_summary", ""),
                "tech_stack": mvp_proposal.tech_stack,
                "architecture": mvp_data.get("architecture", ""),
                "estimated_cost": mvp_cost,
                "estimated_duration": mvp_proposal.estimated_duration,
                "selected_resources": sanitize_resources(mvp_proposal.selected_resources),
                "scope": mvp_proposal.scope,
                "key_features": mvp_data.get("key_features", []),
                "deliverables": mvp_data.get("deliverables", []),
                "assumptions": mvp_proposal.assumptions,
                "risks": mvp_proposal.risks,
                "acceptance_criteria": mvp_data.get("acceptance_criteria", []),
                "status": mvp_proposal.status.value,
                "timeline_phases": mvp_proposal.timeline_phases,
            },
            {
                "id": str(full_proposal.id),
                "proposal_type": full_proposal.proposal_type.value,
                "executive_summary": full_data.get("executive_summary", ""),
                "tech_stack": full_proposal.tech_stack,
                "architecture": full_data.get("architecture", ""),
                "estimated_cost": full_cost,
                "estimated_duration": full_proposal.estimated_duration,
                "selected_resources": sanitize_resources(full_proposal.selected_resources),
                "scope": full_proposal.scope,
                "key_features": full_data.get("key_features", []),
                "deliverables": full_data.get("deliverables", []),
                "assumptions": full_proposal.assumptions,
                "risks": full_proposal.risks,
                "acceptance_criteria": full_data.get("acceptance_criteria", []),
                "status": full_proposal.status.value,
                "timeline_phases": full_proposal.timeline_phases,
            },
        ],
    }

    print(response_data)
    return response_data




def create_proposal_document(
    project_name,
    project_description,
    requirements,
    preferred_technology,
    estimated_budget,
    estimated_duration,
    proposal_type,
    resources,
    tech_stack,
    output_filepath,
):
    try:
        proposal = generate_poc(
            project_name=project_name,
            project_description=project_description,
            requirements=requirements,
            preferred_technology=preferred_technology,
            estimated_budget=estimated_budget,
            estimated_duration=estimated_duration,
            proposal_type=proposal_type,
            resources=resources,
            tech_stack=tech_stack,
        )
    except Exception as e:
        logger.warning(f"Groq API generation failed: {e}. Executing offline mock generation fallback.")
        
        # Parse resources safely
        safe_resources = resources
        if not safe_resources:
            safe_resources = {"resources": []}
        elif not isinstance(safe_resources, dict):
            safe_resources = {"resources": safe_resources}
            
        proposal = {
            "project_name": project_name or "Unknown Project",
            "estimated_cost": float(estimated_budget) if estimated_budget else 0.0,
            "estimated_duration": estimated_duration or "TBD",
            "proposal_type": proposal_type,
            "executive_summary": f"This is an offline generated solution proposal blueprint for {project_name or 'the requested application'}.",
            "scope": f"Scoped development blueprint targeting {project_name or 'the system'} utilizing preferred technologies.",
            "tech_stack": tech_stack or {},
            "timeline_phases": [
                {"Phase": "Architecture Design & Setup", "Duration": "2 Weeks", "Output": "System Blueprint Design"},
                {"Phase": "Core Feature Development", "Duration": "6 Weeks", "Output": "Tested Core APIs and UI"},
                {"Phase": "Integration & Quality Control", "Duration": "4 Weeks", "Output": "Production Release Candidates"}
            ],
            "assumptions": "Standard hosting servers and access keys will be delivered on kickoff.",
            "risks": "Third-party dependency latency limits.",
            "selected_resources": safe_resources
        }

    generate_proposal_docx(
        proposal_data=proposal,
        output_filepath=output_filepath,
    )

    return proposal