import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#626567",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d3e4fe",
        tertiary: "#5c5f61",
        "inverse-primary": "#00dfc4",
        primary: "#006b5d",
        "surface-container-high": "#dce9ff",
        "tertiary-container": "#e2e4e6",
        "on-tertiary-fixed-variant": "#444749",
        "on-primary-container": "#007264",
        "primary-fixed": "#00fee0",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#3f465c",
        surface: "#f8f9ff",
        "on-primary-fixed-variant": "#005046",
        "on-surface-variant": "#3a4a46",
        outline: "#6a7b76",
        secondary: "#565e74",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#bec6e0",
        "primary-container": "#71f5e5",
        "secondary-fixed": "#dae2fd",
        error: "#ba1a1a",
        "on-surface": "#0b1c30",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#131b2e",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#00dfc4",
        "on-primary-fixed": "#00201b",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "tertiary-fixed": "#e0e3e5",
        "surface-tint": "#006b5d",
        "on-error": "#ffffff",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#c4c7c9",
        "secondary-container": "#dae2fd",
        "outline-variant": "#b9cac5",
        "surface-bright": "#f8f9ff",
        "navy-accent": "#0F172A",
        brand: {
          50: "#eaf8f6",
          100: "#d1f1ec",
          200: "#a3e3d8",
          300: "#5fcbb8",
          400: "#2fd6bc",
          500: "#006b5d",
          600: "#00584b",
          700: "#00463b",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "16px",
      },
      spacing: {
        "container-max": "1440px",
        unit: "4px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        gutter: "24px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg": ["Geist"],
        "display-lg-mobile": ["Geist"],
        "body-lg": ["Geist"],
        "headline-md": ["Geist"],
        "body-md": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "button-text": ["Geist"],
      },
      fontSize: {
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "button-text": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
