from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class AgentTextInput(BaseModel):
    text: str = Field(..., description="The unstructured text or transcribed voice input from the user.")
    request_id: Optional[str] = Field(None, description="Optional request ID if continuing an existing chat.") # newly added

class ResourceRequirement(BaseModel):
    role: str = Field(..., description="The role of the resource, e.g., 'Backend Developer'.")
    count: int = Field(..., description="The number of resources needed for this role.")
    skills: List[str] = Field(default_factory=list, description="List of specific skills required, e.g., ['Python', 'FastAPI'].")

class AgentExtractionResponse(BaseModel):
    request_id: Optional[str] = Field(None, description="The unique identifier for the database request if tracked statefully.")
    proposal_id: str = Field(..., description="The unique identifier for the proposal, e.g., 'PROP-001'.")
    project_name: Optional[str] = Field(None, description="The name of the project extracted or generated.")
    business_domain: Optional[str] = Field(None, description="The business domain of the project.")
    project_description: Optional[str] = Field(None, description="The description of the project.")
    preferred_technology: Optional[List[List[str]]] = Field(None, description="List of possible tech stacks, each represented as a list of strings (e.g., [['React', 'FastAPI'], ['Vue', 'Django']]).")
    timeline_days: Optional[int] = Field(None, description="The timeline of the project in days.")
    client_budget: Optional[float] = Field(None, description="The budget of the client in USD.")
    resource_requirements: Optional[List[ResourceRequirement]] = Field(None, description="List of required developers generated by the LLM based on project complexity.")
    
    mvp_timeline_days: Optional[int] = Field(None, description="The dynamically AI-suggested timeline for the MVP phase in days.")
    full_timeline_days: Optional[int] = Field(None, description="The dynamically AI-suggested timeline for the Full project in days.")
    mvp_resource_requirements: Optional[List[ResourceRequirement]] = Field(None, description="List of required developers generated by the LLM for the MVP phase.")
    full_resource_requirements: Optional[List[ResourceRequirement]] = Field(None, description="List of required developers generated by the LLM for the Full project.")
    
    # State flags
    is_gathering_info_complete: bool = Field(False, description="True ONLY when project_name, business_domain, project_description, tech_stack, client_budget, timeline_days, mvp_timeline_days, full_timeline_days, mvp_resource_requirements, and full_resource_requirements are ALL present.")
    summary_confirmed: bool = Field(False, description="True ONLY when the user explicitly agrees to the presented Project Summary.")
    ready_for_match: bool = Field(False, description="True when the summary is confirmed.")
    estimation_confirmed: bool = Field(False, description="True ONLY when the user explicitly agrees to the backend-generated cost and timeline estimation.")
    ready_for_proposal_generation: bool = Field(False, description="True ONLY when estimation is confirmed.")
    
    follow_up_message: str = Field(..., description="Your conversational response to the user. Must ALWAYS be populated.")
    proposal_data: Optional[Dict[str, Any]] = Field(None, description="The generated proposal data if ready_for_proposal_generation is true.")

class NegotiationInput(BaseModel):
    user_request: str = Field(..., description="The user's negotiation request (e.g. 'lower budget by 20%').")
    current_budget: float = Field(..., description="The current budget.")
    current_timeline: str = Field(..., description="The current timeline (e.g. '12 Weeks').")
    current_tech_stack: List[str] = Field(default_factory=list, description="The current tech stack.")

class NegotiationResponse(BaseModel):
    new_budget: float = Field(..., description="The updated budget after negotiation.")
    new_timeline: str = Field(..., description="The updated timeline after negotiation.")
    new_tech_stack: List[str] = Field(..., description="The updated tech stack after negotiation.")
    response_message: str = Field(..., description="The AI's conversational response explaining the adjustments.")
    success: bool = Field(..., description="Whether the negotiation was successful (e.g. false if budget requested is impossibly low).")
    error_message: Optional[str] = Field(None, description="Warning or error message if success is false.")


# ------------------------------------------------------------------
# Budget Negotiation (Tiered Developer Re-Matching)
# ------------------------------------------------------------------

class CurrentResourceItem(BaseModel):
    """Represents one developer currently assigned in the proposal."""
    employee_id: Optional[str] = Field(None, description="Employee UUID from the DB / CSV.")
    name: Optional[str] = Field(None, description="Developer name.")
    role: Optional[str] = Field(None, description="Developer role / designation.")
    hourly_cost: Optional[float] = Field(None, description="Hourly rate in USD.")
    experience_years: Optional[int] = Field(None, description="Years of experience.")
    skills: Optional[List[str]] = Field(default_factory=list, description="Skill list.")
    estimated_cost: Optional[float] = Field(None, description="Cost for the proposal timeline.")
    allocated_hours: Optional[int] = Field(None, description="Total hours allocated to this proposal.")

class BudgetNegotiationInput(BaseModel):
    """
    Payload sent by the frontend when the client asks to reduce the budget.
    Tracks how many times the client has already asked so the backend can
    escalate the strategy (dev swap on attempt 1, timeline extension on attempt 2+).
    """
    request_id: Optional[str] = Field(None, description="The active ProposalRequest UUID in the DB.")
    proposal_type: str = Field("MVP", description="Which proposal variant is being negotiated: 'MVP' or 'FULL'.")
    target_budget: float = Field(..., description="The budget the client is targeting (in USD).")
    current_cost: float = Field(..., description="The current total cost of the proposal (in USD).")
    current_timeline_days: int = Field(..., description="The current project timeline in days.")
    current_resources: List[CurrentResourceItem] = Field(
        default_factory=list,
        description="The full list of developers currently in the proposal so the backend can compute a cost cap."
    )
    resource_requirements: Optional[List[Dict[str, Any]]] = Field(
        None,
        description="Original resource role requirements (role, count, skills, min_experience) from extraction."
    )
    negotiation_attempt: int = Field(
        1,
        description=(
            "1 = first budget reduction request (try cheaper devs first, DO NOT change timeline). "
            "2+ = subsequent requests (extend timeline to reduce cost after devs are already cheapest available)."
        )
    )

class BudgetNegotiationResponse(BaseModel):
    """
    Returned after the backend re-runs resource matching with the new constraints.
    """
    success: bool = Field(..., description="Whether a valid cheaper team was found.")
    strategy_used: str = Field(
        ...,
        description="'developer_swap' if we found cheaper devs, 'timeline_extension' if we extended the timeline."
    )
    new_cost: float = Field(..., description="New total project cost after re-matching.")
    new_timeline_days: int = Field(..., description="New timeline in days (unchanged on attempt 1).")
    new_timeline_formatted: str = Field(..., description="Human-readable timeline string.")
    new_resources: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="The new developer list with updated costs and hourly rates."
    )
    response_message: str = Field(..., description="Conversational message explaining what changed and why.")
    error_message: Optional[str] = Field(None, description="Reason if success is False.")
