from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class AgentTextInput(BaseModel):
    text: str = Field(..., description="The unstructured text or transcribed voice input from the user.")
    request_id: Optional[str] = Field(None, description="Optional request ID if continuing an existing chat.") # newly added

class ResourceRequirement(BaseModel):
    role: str = Field(..., description="The role of the resource, e.g., 'Backend Developer'.")
    count: int = Field(..., description="The number of resources needed for this role.")
    skills: List[str] = Field(default_factory=list, description="List of specific skills required, e.g., ['Python', 'FastAPI'].")

class AgentExtractionResponse(BaseModel):
    request_id: Optional[str] = Field(None, description="The unique identifier for the database request if tracked statefully.")
    proposal_id: str = Field(..., description="The unique identifier for the proposal, e.g., 'PROP-001'.")
    project_name: Optional[str] = Field(None, description="The name of the project extracted or generated.")
    business_domain: Optional[str] = Field(None, description="The business domain of the project.")
    project_description: Optional[str] = Field(None, description="The description of the project.")
    preferred_technology: Optional[List[List[str]]] = Field(None, description="List of possible tech stacks, each represented as a list of strings (e.g., [['React', 'FastAPI'], ['Vue', 'Django']]).")
    timeline_days: Optional[int] = Field(None, description="The timeline of the project in days.")
    client_budget: Optional[float] = Field(None, description="The budget of the client in USD.")
    resource_requirements: Optional[List[ResourceRequirement]] = Field(None, description="List of required developers generated by the LLM based on project complexity.")
    
    mvp_timeline_days: Optional[int] = Field(None, description="The dynamically AI-suggested timeline for the MVP phase in days.")
    full_timeline_days: Optional[int] = Field(None, description="The dynamically AI-suggested timeline for the Full project in days.")
    mvp_resource_requirements: Optional[List[ResourceRequirement]] = Field(None, description="List of required developers generated by the LLM for the MVP phase.")
    full_resource_requirements: Optional[List[ResourceRequirement]] = Field(None, description="List of required developers generated by the LLM for the Full project.")
    
    # State flags
    is_gathering_info_complete: bool = Field(False, description="Set to true ONLY when ALL of these 10 fields are present and non-null: project_name, business_domain, project_description, preferred_technology, client_budget, timeline_days, mvp_timeline_days, full_timeline_days, mvp_resource_requirements, full_resource_requirements. If ANY field is missing or null, this MUST remain false.")
    summary_confirmed: bool = Field(False, description="True ONLY when the user explicitly agrees to the presented Project Summary.")
    ready_for_match: bool = Field(False, description="True when the summary is confirmed.")
    estimation_confirmed: bool = Field(False, description="True ONLY when the user explicitly agrees to the backend-generated cost and timeline estimation.")
    ready_for_proposal_generation: bool = Field(False, description="True ONLY when estimation is confirmed.")
    
    follow_up_message: str = Field(..., description="Your conversational response to the user. Must ALWAYS be populated.")
    proposal_data: Optional[Dict[str, Any]] = Field(None, description="The generated proposal data if ready_for_proposal_generation is true.")

class NegotiationInput(BaseModel):
    user_request: str = Field(..., description="The user's negotiation request (e.g. 'lower budget by 20%').")
    current_budget: float = Field(..., description="The current budget.")
    current_timeline: str = Field(..., description="The current timeline (e.g. '12 Weeks').")
    current_tech_stack: List[str] = Field(default_factory=list, description="The current tech stack.")

class NegotiationResponse(BaseModel):
    new_budget: float = Field(..., description="The updated budget after negotiation.")
    new_timeline: str = Field(..., description="The updated timeline after negotiation.")
    new_tech_stack: List[str] = Field(..., description="The updated tech stack after negotiation.")
    response_message: str = Field(..., description="The AI's conversational response explaining the adjustments.")
    success: bool = Field(..., description="Whether the negotiation was successful (e.g. false if budget requested is impossibly low).")
    error_message: Optional[str] = Field(None, description="Warning or error message if success is false.")
